services:
  adp-backstage-demo1:
    build:
      context: .
      target: production
    image: adp-backstage-demo1
    container_name: adp-backstage-demo1
    environment:
      APPINSIGHTS_CLOUDROLE: adp-backstage-demo1-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
