{{- include "adp-helm-library.container-config-map" (list . "adp-backstage-demo1.config-map") -}}
{{- define "adp-backstage-demo1.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
{{- end -}}
